import { NsCohorts } from "../../../project/ws/app/src/lib/routes/app-toc/models/app-toc.model"

const PROTECTED_SLAG_V8 = `/apis/protected/v8`
const PROXY_SLAG_V8 = `/apis/proxies/v8`
const PUBLIC_SLAG_V8 = `/apis/public/v8`

export const API_END_POINTS = {
  FETCH_USER_GROUPS: (userId: string) =>
    `${PROTECTED_SLAG_V8}/user/group/fetchUserGroup?userId=${userId}`,
  FETCH_USER_ENROLLMENT_LIST: (userId: string | undefined) =>
    `${PROXY_SLAG_V8}/learner/course/v1/user/enrollment/list/${userId}?orgdetails=orgName,email&licenseDetails=name,description,url&fields=contentType,topic,name,channel,mimeType,appIcon,gradeLevel,resourceType,identifier,medium,pkgVersion,thumbnail,board,subject,trackable,posterImage,duration,creatorLogo,license&batchDetails=name,endDate,startDate,status,enrollmentType,createdBy,certificates`,
  SEARCH_V6PUBLIC: `${PUBLIC_SLAG_V8}/ratingsSearch/getCourses`,
  KEYCLOAK_COOKIE: `${PUBLIC_SLAG_V8}/emailMobile/authv2`,
  VALIDATE_CERTIFICATE: `${PUBLIC_SLAG_V8}/certificate/validate`,
  getUserProfile: `${PROXY_SLAG_V8}/api/user/v2/read`,
  USER_SIGNUP: `${PUBLIC_SLAG_V8}/register/registerUserWithEmail`,
  USER_SIGNUP_NEW: `${PROTECTED_SLAG_V8}/user/profileDetails/createUser`,
  REGISTERUSERWITHMOBILE: `${PUBLIC_SLAG_V8}/register/registerUserWithMobile`,
  VERIFY_OTP: `${PUBLIC_SLAG_V8}/register/verifyUserWithMobileNumber`,
  RESET_PASSWORD: `${PUBLIC_SLAG_V8}/register/resetPassword`,
  SETPASSWORD_OTP: `${PUBLIC_SLAG_V8}/register/setPasswordWithOTP`,
  ASSIGN_ADMIN_TO_CREATED_DEPARTMENT: `${PROXY_SLAG_V8}/user/private/v1/assign/role`,
  USER_TNC: `${PROTECTED_SLAG_V8}/user/tnc`,
  FORM_READ: `/apis/v1/form/read?v=${Date.now()}`,
  PLAYLIST_SEARCH: `${PROTECTED_SLAG_V8}/playlist/search?v=${new Date().getTime()}`,
  CONTENT_STATE_READ: `/api/course/v1/content/state/read`,
  PROGRESS_UPDATE: `${PUBLIC_SLAG_V8}/mobileApp/v2/updateProgress`,
  SIGNUP: `${PUBLIC_SLAG_V8}/emailMobile/signup`,
  REGISTER_USERWITH_MOBILE: `${PUBLIC_SLAG_V8}/emailMobile/registerUserWithMobile`,
  GENERATE_OTP: `${PUBLIC_SLAG_V8}/emailMobile/generateOtp`,
  VALIDATE_OTP: `${PUBLIC_SLAG_V8}/emailMobile/validateOtp`,
  VERIFY_FPW_OTP: `${PUBLIC_SLAG_V8}/forgot-password/verifyOtp`,
  RESET_FPW_PASSWORD: `${PUBLIC_SLAG_V8}/forgot-password/reset/proxy/password`,
  SET_FPW_OTP: `${PUBLIC_SLAG_V8}/forgot-password/verifyOtp`,
  profilePid: `${PROXY_SLAG_V8}/api/user/v2/read`,
  newssowithMobileEmail: `${PUBLIC_SLAG_V8}/signupWithAutoLoginV2/register`,
  newssowithMobileEmailOrgForm: `${PUBLIC_SLAG_V8}/signupWithAutoLoginOrgForm/register`,
  validateOTP: `${PUBLIC_SLAG_V8}/signupWithAutoLoginv2/validateOtpWithLogin`,
  validateOrgOTP: `${PUBLIC_SLAG_V8}/signupWithAutoLoginOrgForm/validateOtpWithLogin`,
  sendUserOTP: `${PUBLIC_SLAG_V8}/ssoLogin/otp/sendOtp`,
  newLogin: `${PUBLIC_SLAG_V8}/ssoLogin/login`,
  resendOTP: `${PUBLIC_SLAG_V8}/ssoLogin/otp/resendOtp`,
  EMAIL_TEXT: `${PROTECTED_SLAG_V8}/user/email/emailText`, // #POST
  EMAIL_TO_USERID: `${PROTECTED_SLAG_V8}/user/emailToUserId`,
  USER_FOLLOW_DATA: `${PROTECTED_SLAG_V8}/user/follow/fetchAll`, // #GET
  USER_FOLLOW: `${PROTECTED_SLAG_V8}/user/follow`, // #POST
  USER_UNFOLLOW: `${PROTECTED_SLAG_V8}/user/follow/unfollow`, // #POST
  LOGOUT_USER: `${PROXY_SLAG_V8}/logout/user`,
  webview_login: `apis/public/v8/mobileApp/webviewLogin`,
  AUTH_CONTENT: (path: any) => `/apis/authContent/${path}`,
  createContentDirectory: (contentId: string) => `${PROTECTED_SLAG_V8}/user/exercise/createContentDirectory/${contentId}`,
  postSubmission: (contentId: string) => `${PROTECTED_SLAG_V8}/user/exercise/postsubmission/${contentId}`,
  uploadFile: (contentId: string) => `${PROTECTED_SLAG_V8}/user/exercise/uploadFileToContentDirectory/${contentId}`,
  get_Submissions: (type: string, contentId: string) => `${PROTECTED_SLAG_V8}/user/exercise/getSubmissions?type=${type}&contentId=${contentId}`,
  ASSESSMENT_SUBMIT_V2: `${PROTECTED_SLAG_V8}/assessment/submit/v2`,
  UPDATE_PASSBOOK: `${PROXY_SLAG_V8}/user/v1/passbook`,
  COMPETENCY_ASSESSMENT_SUBMIT_V2: `apis/protected/v8/assessmentCompetency/v1/assessment/submit`,
  SCROM_ADD_UPDTE: `${PROTECTED_SLAG_V8}/scrom/add`,
  SCROM_FETCH: `${PROTECTED_SLAG_V8}/scrom/get`,
  SCROM_FETCH_PROGRESS: `${PROXY_SLAG_V8}/read/content-progres`,
  NEW_PROGRESS_UPDATE: `${PROTECTED_SLAG_V8}/updateProgressv2/update`,
  setS3Cookie: `/apis/v8/protected/content/setCookie`,
  UPDATE_PROGRESS: `${PROXY_SLAG_V8}/content-progres`,
  NEW_PROGRESS_UPDATE_V3: `${PROTECTED_SLAG_V8}/updateProgressv3/update`,
  SCORM_UPDATE: `${PROXY_SLAG_V8}/getContents/`,
  CATALOG_AUTHORING: `${PROTECTED_SLAG_V8}/social/catalog`,
  USER_ROLE: `${PROTECTED_SLAG_V8}/user/roles`,
  ACCESS_CONTROL: `${PROTECTED_SLAG_V8}/user/accessControl`,
  PROGRESS_HASH: `${PROTECTED_SLAG_V8}/user/progress`,
  AUTOCOMPLETE: (query: string) => `${PROTECTED_SLAG_V8}/user/autocomplete/${query}`,
  USER_SHARE: `${PROTECTED_SLAG_V8}/user/share`,
  USER_CONTENT_SHARE: `${PROTECTED_SLAG_V8}/user/share/content`,

  CONTENT: `${PROTECTED_SLAG_V8}/content`,
  AUTHORING_CONTENT: `/apis/authApi/hierarchy`,
  LATEST_HOMEPAGE_COURSE: `${PUBLIC_SLAG_V8}/homePage/latestCourses`,
  CONTENT_LIKES: `${PROTECTED_SLAG_V8}/content/likeCount`,
  SET_S3_COOKIE: `${PROTECTED_SLAG_V8}/content/setCookie`,
  SET_S3_IMAGE_COOKIE: `${PROTECTED_SLAG_V8}/content/setImageCookie`,
  FETCH_MANIFEST: `${PROTECTED_SLAG_V8}/content/getWebModuleManifest`,
  FETCH_WEB_MODULE_FILES: `${PROTECTED_SLAG_V8}/content/getWebModuleFiles`,
  MULTIPLE_CONTENT: `${PROTECTED_SLAG_V8}/content/multiple`,
  CONTENT_SEARCH_V5: `${PROTECTED_SLAG_V8}/content/searchV5`,
  PUBLIC_CONTENT_SEARCH: `${PUBLIC_SLAG_V8}/ratingsSearch/getCourses`,
  CONTENT_SEARCH: `${PUBLIC_SLAG_V8}/mobileApp/contentSearch`,
  CONTENT_SEARCH_V6: `${PROXY_SLAG_V8}/sunbirdigot/read`,
  CONTENT_SEARCH_REGION_RECOMMENDATION: `${PROTECTED_SLAG_V8}/content/searchRegionRecommendation`,
  CONTENT_HISTORY: `${PROTECTED_SLAG_V8}/user/history`,
  CONTENT_HISTORYV2: `${PROXY_SLAG_V8}/read/content-progres`,
  USER_CONTINUE_LEARNING: `${PROTECTED_SLAG_V8}/user/history/continue`,
  CONTENT_RATING: `${PROTECTED_SLAG_V8}/user/rating`,
  COLLECTION_HIERARCHY: (type: string, id: string) =>
    `${PROTECTED_SLAG_V8}/content/collection/${type}/${id}`,
  REGISTRATION_STATUS: `${PROTECTED_SLAG_V8}/admin/userRegistration/checkUserRegistrationContent`,
  MARK_AS_COMPLETE_META: (contentId: string) => `${PROTECTED_SLAG_V8}/user/progress/${contentId}`,
  COURSE_BATCH_LIST: `${PROXY_SLAG_V8}/learner/course/v1/batch/list`,
  ENROLL_BATCH: `${PROXY_SLAG_V8}/learner/course/v1/enrol`,
  COURSE_RATING: `${PROTECTED_SLAG_V8}/ratings/upsert`,
  READ_COURSE_RATING: `${PROTECTED_SLAG_V8}/ratings/v2/read`,
  READ_COURSE_RATING_SUMMARY: `${PROTECTED_SLAG_V8}/ratings/summary`,
  GOOGLE_AUTHENTICATE: `${PUBLIC_SLAG_V8}/google/callback`,
  LOGIN_USER: `${PUBLIC_SLAG_V8}/emailMobile/auth`,
  FETCH_USER_ENROLLMENT_LIST_COMP: (userId: string | undefined) =>
    `${PROXY_SLAG_V8}/learner/course/v1/user/enrollment/list/${userId}?orgdetails=orgName,email&licenseDetails=name,description,url&fields=competency,contentType,sourceName,issueCertification,topic,name,channel,mimeType,appIcon,gradeLevel,resourceType,thumbnail,identifier,medium,pkgVersion,board,subject,trackable,posterImage,duration,creatorLogo,license,competency&batchDetails=name,endDate,startDate,status,enrollmentType,createdBy,certificates`,
  FETCH_GENERAL_RC_CERTIFICATE: () =>
    // tslint:disable-next-line: max-line-length
    `apis/protected/v8/rcCert/user/enrollment/list/adhocCertificates?orgdetails=orgName,email&licenseDetails=name,description,url&fields=competency,contentType,sourceName,issueCertification,topic,name,channel,mimeType,appIcon,gradeLevel,resourceType,thumbnail,identifier,medium,pkgVersion,board,subject,trackable,posterImage,duration,creatorLogo,license,competency&batchDetails=name,endDate,startDate,status,enrollmentType,createdBy,certificates`,
  COURSE_RECOMENDATION: (profession: string) =>
    `${PUBLIC_SLAG_V8}/mobileApp/courseRemommendationv2?profession=${profession}`,
  COURSE_RECOMMENDATION_V2: `${PUBLIC_SLAG_V8}/mobileApp/publicSearch/courseRecommendationCbp`,
  CONTENT_READ: (id: string) => `${PROXY_SLAG_V8}/action/content/v3/read/${id}`,
  CONTENT_HIERARCHY: (contentId: string, type: string) => `${PROXY_SLAG_V8}/action/content/v3/hierarchy/${contentId}?hierarchyType=${type}`,
  BATCH_CERT_ISSUE: `${PROXY_SLAG_V8}/course/batch/cert/v1/issue/`,
  DOWNLOAD_CERTIFICATE: (certificateId: string) => `${PROXY_SLAG_V8}/certreg/v2/certs/download/${certificateId}`,
  FETCH_USER_ENROLLMENT_LIST_CERT: (userId: string | undefined) =>
    `${PROXY_SLAG_V8}/learner/course/v1/user/enrollment/list/${userId}?orgdetails=orgName,email&licenseDetails=name,description,url&fields=competency,contentType,topic,name,channel,mimeType,appIcon,gradeLevel,resourceType,identifier,medium,pkgVersion,thumbnail,board,subject,trackable,posterImage,duration,creatorLogo,license,sourceName,issueCertification,competency&batchDetails=name,endDate,startDate,status,enrollmentType,createdBy,certificates`,
  FETCH_USER_ENROLLMENT_LIST_V2: (userId: string | undefined, orgdetails: string, licenseDetails: string, fields: string, batchDetails: string) =>
    `apis/proxies/v8/learner/course/v1/user/enrollment/list/${userId}?orgdetails=${orgdetails}&licenseDetails=${licenseDetails}&fields=${fields}&batchDetails=${batchDetails}`,
  assignContent: `${PROTECTED_SLAG_V8}/user/content-assign/assignContent`,
  getAdminLevel: `${PROTECTED_SLAG_V8}/user/content-assign/getAdminLevel`,
  getAssignments: `${PROTECTED_SLAG_V8}/user/content-assign/getAssignments`,
  searchUsers: `${PROTECTED_SLAG_V8}/user/content-assign/searchUsers`,
  managerDetails: `${PROTECTED_SLAG_V8}/user/details/managerDetails`,
  SOCIAL_TIMELINE: `${PROTECTED_SLAG_V8}/social/post/timeline`,
  SOCIAL_VIEW_CONVERSATION: `${PROTECTED_SLAG_V8}/social/post/viewConversation`,
  SOCIAL_VIEW_CONVERSATION_V2: `${PROTECTED_SLAG_V8}/social/post/viewConversationV2`,
  SOCIAL_POST_PUBLISH: `${PROTECTED_SLAG_V8}/social/post/publish`,
  SOCIAL_POST_DELETE: `${PROTECTED_SLAG_V8}/social/post/delete`,
  SOCIAL_POST_ACTIVITY_UPDATE: `${PROTECTED_SLAG_V8}/social/post/activity/create`,
  SOCIAL_POST_ACTIVITY_USERS: `${PROTECTED_SLAG_V8}/social/post/activity/users`,
  SOCIAL_POST_UPDATE: `${PROTECTED_SLAG_V8}/social/edit/meta`,
  REMOVE_SUBSET: `${PROTECTED_SLAG_V8}/content/removeSubset`,
  catalog: `${PUBLIC_SLAG_V8}/homePage/catalog`,
  SET_COOKIE: `${PROTECTED_SLAG_V8}/content/setCookie`,
  GET_CONTENT: (id: string) => `${PROTECTED_SLAG_V8}/content/${id}?hierarchyType=minimal`,
  sharePointToken: `${PROTECTED_SLAG_V8}/user/token`,
  PUBLIC_TELEMETRY: `${PUBLIC_SLAG_V8}/publicTelemetry`,
  userPref: `${PROTECTED_SLAG_V8}/user/preference`,
  TNC_ACCEPT: `${PROTECTED_SLAG_V8}/user/tnc/accept`,
  TNC_POST_PROCESSING: `${PROTECTED_SLAG_V8}/user/tnc/postprocessing`,
  BATCH_CREATE: `${PROXY_SLAG_V8}/learner/course/v1/batch/create`,
  CONTENT_PARENTS: `${PROTECTED_SLAG_V8}/content/parents`,
  CONTENT_NEXT: `${PROTECTED_SLAG_V8}/content/next`,
  CONTENT_PARENT: (contentId: string) => `${PROTECTED_SLAG_V8}/content/${contentId}/parent`,
  CONTENT_AUTH_PARENT: (contentId: string, rootOrg: string, org: string) =>
    `/apis/authApi/action/content/parent/hierarchy/${contentId}?rootOrg=${rootOrg}&org=${org}`,
  COHORTS: (cohortType: NsCohorts.ECohortTypes, contentId: string) =>
    `${PROTECTED_SLAG_V8}/cohorts/${cohortType}/${contentId}`,
  EXTERNAL_CONTENT: (contentId: string) =>
    `${PROTECTED_SLAG_V8}/content/external-access/${contentId}`,
  COHORTS_GROUP_USER: (groupId: number) => `${PROTECTED_SLAG_V8}/cohorts/${groupId}`,
  RELATED_RESOURCE: (contentId: string, contentType: string) =>
    `${PROTECTED_SLAG_V8}/khub/fetchRelatedResources/${contentId}/${contentType}`,
  POST_ASSESSMENT: (contentId: string) =>
    `${PROTECTED_SLAG_V8}/user/evaluate/post-assessment/${contentId}`,
  CONTENT_ANALYTICS: (contentId: string) => `${PROXY_SLAG_V8}/LA/api/la/contentanalytics?content_id=${contentId}&type=course`,
  LA_LA_USER: `${PROXY_SLAG_V8}/LA/LA/api/Users`,
  SEARCH_V7PUBLIC: `${PUBLIC_SLAG_V8}/publicSearch/getCourses`,
  Sashakt_Auth: `${PUBLIC_SLAG_V8}/sashaktAuth/login`,
  Maternity_Auth: `${PUBLIC_SLAG_V8}/maternityFoundation/login`,
  ENROLLED_USER: `apis/protected/v8/userEnrolledInSource`,
  Tnai_Auth: `${PUBLIC_SLAG_V8}/tnai/login`,
  MNC_Auth: `${PUBLIC_SLAG_V8}/mnc/login`,
  Tnnmc_Auth: `${PUBLIC_SLAG_V8}/tnnmc/login`,
  userTopics: `${PROTECTED_SLAG_V8}/user/topics`,
  lastlearnt: `${PROTECTED_SLAG_V8}/user/history`,
  getFollowersv3: `${PROTECTED_SLAG_V8}/user/follow/getFollowersv3`,
  getFollowingv3: `${PROTECTED_SLAG_V8}/user/follow/getFollowingv3`,
  getFollowing: `${PROTECTED_SLAG_V8}/user/follow/getFollowing`,
  getAllPlaylists: `${PROTECTED_SLAG_V8}/user/playlist`,
  getDetails: `${PROTECTED_SLAG_V8}/user/details/detailV2`,
  VALIDATE_USER: `${PROTECTED_SLAG_V8}/user/validate`,
  NOTIFICATIONS: `${PROTECTED_SLAG_V8}/user/notifications/settings`,
  USER_ORG_GRAPH: `${PROTECTED_SLAG_V8}/user/dashboard/userOrgTime`,
  TIME_SPENT: `/api/timespent`,
  NSO_PROGRESS: `/api/nsoArtifactsAndCollaborators`,
  SKILL_DATA: `/api/managerRecommendedSkills`,
  SOCIAL_VIEW_SEARCH_RESULT: `${PROTECTED_SLAG_V8}/social/post/search`,
  SEARCH_V6: `${PROTECTED_SLAG_V8}/content/searchV6`,
  SEARCH_V8PUBLIC: `${PUBLIC_SLAG_V8}/ratingsSearch/recommendation/publicSearch/getcourse`,
  translateFilters: (lang: string) => `${PROTECTED_SLAG_V8}/translate/filterdata/${lang}`,
  updateProfileDetails: `${PROTECTED_SLAG_V8}/user/profileDetails/updateUser`,
  updateProfileWithSourceDetails: `${PROTECTED_SLAG_V8}/user/profileDetails/v2/updateUser`,
  getUserdetailsFromRegistry: `${PROXY_SLAG_V8}/api/user/v2/read`,
  getUserdetails: `${PROTECTED_SLAG_V8}/user/details/detailV1`,
  getMasterNationlity: `${PROTECTED_SLAG_V8}/user/profileRegistry/getMasterNationalities`,
  getMasterLanguages: `${PROTECTED_SLAG_V8}/user/profileRegistry/getMasterLanguages`,
  getAllDepartments: `${PROTECTED_SLAG_V8}/portal/listDeptNames`,
  approveRequest: `${PROTECTED_SLAG_V8}/workflowhandler/transition`,
  getPendingFields: `${PROTECTED_SLAG_V8}/workflowhandler/userWFApplicationFieldsSearch`,
  bnrcRegistration: `${PUBLIC_SLAG_V8}/bnrcUserCreation/createUser`,
  bnrcSendOtpRegistration: `${PUBLIC_SLAG_V8}/bnrcUserCreation/otp/sendOtp`,
  bnrcReSendOtpRegistration: `${PUBLIC_SLAG_V8}/bnrcUserCreation/otp/resendOtp`,
  bnrcValidateOtpRegistration: `${PUBLIC_SLAG_V8}/bnrcUserCreation/otp/validateOtp`,
  upsmfRegistration: `${PUBLIC_SLAG_V8}/upsmfUserCreation/createUser`,
  upsmfSendOtpRegistration: `${PUBLIC_SLAG_V8}/upsmfUserCreation/otp/sendOtp`,
  upsmfReSendOtpRegistration: `${PUBLIC_SLAG_V8}/upsmfUserCreation/otp/resendOtp`,
  upsmfValidateOtpRegistration: `${PUBLIC_SLAG_V8}/upsmfUserCreation/otp/validateOtp`,
  mpRegistration: `${PUBLIC_SLAG_V8}/mpNHMUserCreation/createUser`,
  mpSendOtpRegistration: `${PUBLIC_SLAG_V8}/mpNHMUserCreation/otp/sendOtp`,
  mpReSendOtpRegistration: `${PUBLIC_SLAG_V8}/mpNHMUserCreation/otp/resendOtp`,
  mpValidateOtpRegistration: `${PUBLIC_SLAG_V8}/mpNHMUserCreation/otp/validateOtp`,
  getLeaderBoardData: `${PROXY_SLAG_V8}/user/v1/leaderboard`,

}

export const S3_END_POINTS = {
  ORG_SELECTIVE_COURSE: `https://aastar-assets.s3.ap-south-1.amazonaws.com/data/org-selective-course.json?cb=${Date.now()}`,
  // SPHERE_PROFILE_UPDATE_ORG: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/sphere_profile_update_org.json`,
  // EKSHAMATA_ORG_CONFIG: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/ekshamataOrgConfig.json`,
  QUIZ_CONFIG: `https://aastar-assets.s3.ap-south-1.amazonaws.com/data/quiz-config.json?cb=${Date.now()}`,
  CONTACT_PAGE_CONFIG: `https://aastar-assets.s3.ap-south-1.amazonaws.com/data/contact-page-content.json?v=${Date.now()}`,
  UP_DISTRICT_CONFIG: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/up_District.json?cb=${Date.now()}`,
  mpANMDistrictUrl: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/mp_anm_District.json?cb=${Date.now()}`,
  mpCHODistrictUrl: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/mp_cho_District.json?cb=${Date.now()}`,
  mpTRAINERDistrictUrl: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/mp_trainer_district.json?cb=${Date.now()}`,
  biharDistrictUrl: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/bihar-district.json?cb=${Date.now()}`,
  instituteNameUrl: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/bnrc-institute.json?cb=${Date.now()}`,
  ORG_META_CONFIG: `https://aastar-app-assets.s3.ap-south-1.amazonaws.com/orgMeta.json?cb=${Date.now()}`,
}
