sonar.projectKey=Sphere_eagle-fusion
sonar.organization=sphere
sonar.projectName=eagle-fusion
sonar.projectVersion=0.0.1
sonar.host.url=https://sonarcloud.io

# Sources and tests
sonar.sources=src,library,project
sonar.tests=src,library,project
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/*.mock.ts,\
  **/e2e/**,\
  **/docs/**,\
  **/.angular/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# ESLint
sonar.eslint.reportPaths=eslint-report.json
