sonar.projectKey=Sphere_eagle-fusion-src
sonar.projectName=eagle-fusion-src
sonar.projectVersion=0.0.1
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/*.mock.ts,\
  **/e2e/**,\
  **/docs/**,\
  **/.angular/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
