version: 2.1

on:
  pull_request:
    types: [opened,reopened]

executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts
      
jobs:
  build-check:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          checkout
          yarn
          npm run lint:fix
          npm build

workflows:
  my-custom-workflow:
    jobs:
      - build-check