version: 2

jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.22.9-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: yarn
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint:fix
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: |
                    npm run build
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist

    

workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - baseline-2.0
            # The deploy job will only run on the filtered branches and
            # require the build job to be successful before it starts
          
                