export const ICON_TYPE = {
  program: 'library_books',
  course: 'book',
  learningModule: 'folder',
  certificate: 'chrome_reader_mode',
  externalContent: 'web',
  internalContent: 'input',
  pdf: 'picture_as_pdf',
  youtube: 'subscriptions',
  assessment: 'assessment',
  quiz: 'assignment_turned_in',
  dragNDrop: 'swap_vertical_circle',
  htmlPicker: 'web_asset',
  handsOn: 'code',
  iap: 'assignment_late',
  audio: 'audiotrack',
  video: 'video_library',
  default: 'file_copy',
  emptyFile: 'insert_drive_file',
  channel: 'chrome_reader_mode',
  kBoard: 'amp_stories',
}
