export const MIME_TYPE = {
  collection: 'application/vnd.ekstep.content-collection',
  ecml: 'application/vnd.ekstep.ecml-archive',
  ePub: 'application/epub',
  h5p: 'application/vnd.ekstep.h5p-archive',
  html: 'application/html',
  ilpfp: 'application/ilpfp',
  iap: 'application/iap-assessment',
  mp3: 'audio/mpeg',
  mp4: 'application/x-mpegURL',
  interaction: 'video/interactive',
  pdf: 'application/pdf',
  quiz: 'application/quiz',
  webm: 'video/webm',
  webModule: 'application/web-module',
  youtube: 'video/x-youtube',
  handson: 'application/integrated-hands-on',
  htmlPicker: 'application/htmlpicker',
  dragDrop: 'application/drag-drop',
}
